"""add test table

Revision ID: 2d4c11e9a67d
Revises:
Create Date: 2026-07-23 15:37:02.998906

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2d4c11e9a67d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("checkpoint_index")
    op.drop_table("checkpoint_nav")
    op.alter_column(
        "fund_index", "fund_house", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "fund_index", "scheme_type", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "fund_index", "scheme_category", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "fund_index", "scheme_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "fund_index", "scheme_start_date", existing_type=sa.DATE(), nullable=False
    )
    op.drop_column("fund_index", "nav")
    op.alter_column(
        "historical_nav", "scheme_code", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "historical_nav", "nav_date", existing_type=sa.DATE(), nullable=False
    )
    op.alter_column(
        "historical_nav",
        "nav",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        nullable=False,
    )
    op.drop_constraint(
        op.f("historical_nav_scheme_code_nav_date_key"),
        "historical_nav",
        type_="unique",
    )
    op.drop_column("historical_nav", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "historical_nav",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.create_unique_constraint(
        op.f("historical_nav_scheme_code_nav_date_key"),
        "historical_nav",
        ["scheme_code", "nav_date"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "historical_nav",
        "nav",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        nullable=True,
    )
    op.alter_column(
        "historical_nav", "nav_date", existing_type=sa.DATE(), nullable=True
    )
    op.alter_column(
        "historical_nav", "scheme_code", existing_type=sa.INTEGER(), nullable=True
    )
    op.add_column(
        "fund_index", sa.Column("nav", sa.REAL(), autoincrement=False, nullable=True)
    )
    op.alter_column(
        "fund_index", "scheme_start_date", existing_type=sa.DATE(), nullable=True
    )
    op.alter_column(
        "fund_index", "scheme_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "fund_index", "scheme_category", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "fund_index", "scheme_type", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "fund_index", "fund_house", existing_type=sa.VARCHAR(), nullable=True
    )
    op.create_table(
        "checkpoint_nav",
        sa.Column("scheme_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "last_synced",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.VARCHAR(length=20),
            server_default=sa.text("'COMPLETED'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["scheme_code"],
            ["fund_index.scheme_code"],
            name=op.f("checkpoint_nav_scheme_code_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("scheme_code", name=op.f("checkpoint_nav_pkey")),
    )
    op.create_table(
        "checkpoint_index",
        sa.Column("scheme_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "completed_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("scheme_code", name=op.f("checkpoint_index_pkey")),
    )
    op.drop_table("test")
    # ### end Alembic commands ###
